server:
   port: 4001
   
spring:
   application:
       name: zull-server

eureka:
   instance:
       hostname: 192.168.246.146
       prefer-ip-address: true
   client:
       healthcheck: 
            enabled: true
       serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:4000/eureka/

zuul:
   host:
        connect-timeout-millis: 3000
        socket-timeout-millis: 3000
   routes:
       order-service: /orderservice/**
       member-service: /memberservice/**
       thorn6-m6: /m6/**

ribbon:
   ReadTimeout: 3000
   ConnectTimeout: 3000
       