server:
  port: 4002
eureka:
  client:
    healthcheck:
      enabled: true
spring:
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      percentage: 1.0
zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    order-service: /orderservice/**
    member-service: /memberservice/**
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000