server:
   port: 9080
   
spring:
    application: 
        name: MemberService

eureka:
   instance:
       hostname: localhost
   client:
       serviceUrl:
           defaultZone: http://localhost:4000/eureka/