server:
   port: 9080
   
spring:
    application: 
        name: member-service

eureka:
   instance:
       hostname: localhost
   client:
       healthcheck: 
            enabled: true
       serviceUrl:
           defaultZone: http://localhost:4000/eureka/