server:
   port: 9081
   
spring:
    application: 
        name: order-service

eureka:
   instance:
       hostname: localhost
       prefer-ip-address: true
   client:
       healthcheck: 
            enabled: true
       serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:4000/eureka/