server:
  port: 9081
eureka:
  client:
    healthcheck:
      enabled: true
spring:
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      percentage: 1.0
ribbon:
  hystrix:
    enabled: true
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'