server:
  port: 9411
spring:
  application:
    name: zipkin-server
  zipkin:
    enabled: false
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:4000/eureka/