server:
   port: 4000
   
spring:
    application: 
        name: eureka-server

# Eureka 注册中心访问配置
eureka:
   instance:
       hostname: 192.168.246.146
   client:
       registerWithEureka: false
       fetchRegistry: false
       serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
           
management:
   security: 
       enabled: false